language: php

env:
    global:
        - SYMFONY_DEPRECATIONS_HELPER: weak

php:
  - 5.6

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

branches:
  only:
    - master
    - dev
    - /^\d+\.\d+$/

matrix:
  fast_finish: true
  include:
    - php: 5.6
      env: COMPOSER_FLAGS="--prefer-lowest"

before_install:
  - composer self-update
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require --dev --no-update symfony/symfony=$SYMFONY_VERSION; fi

install: composer update $COMPOSER_FLAGS --prefer-dist

script: if [ "$TRAVIS_PHP_VERSION" == "5.6" ]; then phpunit --coverage-clover=coverage.clover; else phpunit; fi
